import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.net.ServerSocket;
import java.net.Socket;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;
import java.net.URL;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 * @author Luke Ahrens-Townsend
 * Date: April 20, 2017
 */

public class TCPMessengerServer extends javax.swing.JFrame {
    
    ServerSocket serverSocket;
    Socket clientSocket;
    int portNumber = 12000;
    String clientAddress, inputLine, outputLine;
    String userName = "Server";   
    BufferedReader in;
    PrintWriter out;   
    Timer connectionStart;
    boolean connected = false;
    boolean talking = false;
    int initMsg = 0;   
    ImageIcon icon;

    /**
     * Creates new form TCPMessengerServer
     */
    public TCPMessengerServer() {
        initComponents();
        customInitComponents();
        listenForClient();               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msgInputArea = new javax.swing.JTextArea();
        msgSendButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgDisplayArea = new javax.swing.JTextArea();
        userNameLabel = new javax.swing.JLabel();
        userNameArea = new javax.swing.JTextField();
        userNameButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TCP Messenger - Server");
        setIconImage(setIcon());
        setLocation(new java.awt.Point(75, 100));
        setMinimumSize(new java.awt.Dimension(400, 440));
        setName("TCPMessengerServer"); // NOI18N
        setPreferredSize(new java.awt.Dimension(454, 475));

        msgInputArea.setColumns(20);
        msgInputArea.setLineWrap(true);
        msgInputArea.setRows(1);
        msgInputArea.setWrapStyleWord(true);
        msgInputArea.setNextFocusableComponent(userNameArea);
        msgInputArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                msgInputAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(msgInputArea);

        msgSendButton.setText("Send");
        msgSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgSendButtonActionPerformed(evt);
            }
        });

        msgDisplayArea.setEditable(false);
        msgDisplayArea.setColumns(20);
        msgDisplayArea.setLineWrap(true);
        msgDisplayArea.setText("Waiting for connection from client...");
        msgDisplayArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(msgDisplayArea);

        userNameLabel.setText("Your name:");

        userNameArea.setNextFocusableComponent(msgInputArea);
        userNameArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameAreaFocusLost(evt);
            }
        });
        userNameArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameAreaActionPerformed(evt);
            }
        });
        userNameArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameAreaKeyTyped(evt);
            }
        });

        userNameButton.setText("Submit");
        userNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msgSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(userNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userNameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgSendButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        userNameLabel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msgSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgSendButtonActionPerformed
        sendMessage();
    }//GEN-LAST:event_msgSendButtonActionPerformed

    private void msgInputAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msgInputAreaKeyTyped
        if (evt.getKeyChar() == '\n')
            sendMessage();
    }//GEN-LAST:event_msgInputAreaKeyTyped

    private void userNameAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameAreaActionPerformed

    private void userNameAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameAreaKeyTyped
        if (evt.getKeyChar() == '\n')
            setUserName();
        
        Timer t = new Timer();
        t.schedule(new TimerTask() {
            public void run() {
                if (!userNameArea.getText().equals(userName)) {
                    userNameArea.setForeground(new Color(187, 187, 187));
                } else {
                    userNameArea.setForeground(new Color(0, 195, 0));
                }
            }
        }, 5);
    }//GEN-LAST:event_userNameAreaKeyTyped

    private void userNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameButtonActionPerformed
        setUserName();
    }//GEN-LAST:event_userNameButtonActionPerformed

    private void userNameAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameAreaFocusGained

    }//GEN-LAST:event_userNameAreaFocusGained

    private void userNameAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameAreaFocusLost
        userNameArea.setText(userName);
        userNameArea.setForeground(new Color(0, 195, 0));
    }//GEN-LAST:event_userNameAreaFocusLost

    private void customInitComponents() {
        Color mainBackground = new Color(60, 63, 65);
        Color textFieldBackground = new Color(69, 73, 74);
        Color textSelection = new Color(75, 110, 175);
        Font plainTextFont = new Font("Dialog", Font.PLAIN, 12);
        Font boldTextFont = new Font("Dialog", Font.BOLD, 12);
        Color fontColor = new Color(187, 187, 187);
        
        getContentPane().setBackground(mainBackground);
        
        userNameLabel.setFont(boldTextFont);
        userNameLabel.setForeground(fontColor); 
        
        userNameArea.setFont(plainTextFont);
        userNameArea.setBackground(textFieldBackground);
        userNameArea.setForeground(fontColor);
        userNameArea.setSelectedTextColor(fontColor);
        userNameArea.setSelectionColor(textSelection);
        
        userNameButton.setFont(boldTextFont);
        userNameButton.setBackground(mainBackground);
        userNameButton.setForeground(fontColor);
        
        msgDisplayArea.setFont(plainTextFont);
        msgDisplayArea.setBackground(textFieldBackground);
        msgDisplayArea.setForeground(fontColor);
        msgDisplayArea.setSelectedTextColor(fontColor);
        msgDisplayArea.setSelectionColor(textSelection);

        msgInputArea.setFont(plainTextFont);
        msgInputArea.setBackground(textFieldBackground);
        msgInputArea.setForeground(fontColor);
        msgInputArea.setSelectedTextColor(fontColor);
        msgInputArea.setSelectionColor(textSelection);

        msgSendButton.setFont(boldTextFont);
        msgSendButton.setBackground(mainBackground);
        msgSendButton.setForeground(fontColor);
    }
    
    private void listenForClient() {
        connectionStart = new Timer();        
        connectionStart.schedule(new TimerTask() {
            public void run() {
                try {              
                    createConnection();
                } catch (IOException ex) {
                    Logger.getLogger(TCPMessengerServer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }, 1000);
    }
    
    private void createConnection() throws IOException {
        serverSocket = new ServerSocket(portNumber);
        clientSocket = serverSocket.accept();
        in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
        out = new PrintWriter(clientSocket.getOutputStream(), true);
        
        if (clientSocket.isConnected()) {
            out.println("Connection successful.");
            clientAddress = String.valueOf(clientSocket.getLocalAddress());
            msgDisplayArea.append("\nConnection successful. (" + clientAddress.substring(1, clientAddress.length()) + ", " + portNumber + ")");                      
            connectionStart.cancel();
            connected = true; 
            
            listenForMessages();           
        }           
    }
    
    private void listenForMessages() {
        Timer msgRecvUpdate = new Timer();
        
        msgRecvUpdate.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                try {
                    receiveMessage();
                } catch (IOException ex) {
                    connected = false;
                    Logger.getLogger(TCPMessengerServer.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                if (!connected) {
                    msgDisplayArea.append("\n\nConnection closed.");
                    autoScroll();
                    msgRecvUpdate.cancel();
                }
            }
        }, 50, 200);
    }
    
    private void receiveMessage() throws IOException {
        if ((inputLine = in.readLine()) != null) {
            if (talking || initMsg == 0) {
                msgDisplayArea.append("\n\n");
                initMsg = 1;
            } else {
                msgDisplayArea.append("\n");
            }
                        
            msgDisplayArea.append(inputLine);                        
            talking = false;
            autoScroll();
        }
    }
    
    private void sendMessage() {
        if (!msgInputArea.getText().equals("\n") && !msgInputArea.getText().equals("") && connected) {
            outputLine = msgInputArea.getText();           
            
            if (!talking) {
                out.printf(userName + ": " + outputLine);
                msgDisplayArea.append("\n\n" + userName + ": ");
            } else {
                out.printf(outputLine);
                msgDisplayArea.append("\n");
            }
            
            outputLine = outputLine.substring(0, outputLine.length() - 1);
            msgDisplayArea.append(outputLine);
            talking = true;            
        }
        
        msgInputArea.setText("");
        autoScroll();
    }
    
    private void setUserName() {
        userName = userNameArea.getText();
        userNameArea.setForeground(new Color(0, 195, 0));
        msgInputArea.transferFocusBackward();
    }
    
    private void autoScroll() {
        msgDisplayArea.setSelectionStart(msgDisplayArea.getText().length());
    }
    
    private Image setIcon() {
        URL iconURL = getClass().getResource("skywalker.png");
        icon = new ImageIcon(iconURL);
        return icon.getImage();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCPMessengerServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCPMessengerServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCPMessengerServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCPMessengerServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCPMessengerServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea msgDisplayArea;
    private javax.swing.JTextArea msgInputArea;
    private javax.swing.JButton msgSendButton;
    private javax.swing.JTextField userNameArea;
    private javax.swing.JButton userNameButton;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
